### ISSUE TITLE
Adjust theme to account for natural border width scaling

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1584]
We need to tweak our theme a little to account for 27.7+'s natural border width scaling.
Specifically, this causes issues with tab borders because they are actually 2 px wide at the base (with 1 transparent) which means that at 125% it scales up to 3, making it round up (1.5->2).

Instead of 2px we have now, we probably need to use 1.6px, so it scales more narrowly as-if it was actually a simple single-pixel border. 1.6 will scale to 2.0 at 125%, and 2.4 (still rounding to 2) at 150%, so we stay within the 2 px region for the two common dpi change ranges.

Suggested changes:
``` CSS
.tabbrowser-tab,
.tabs-newtab-button {
  border: 1.6px solid; /* was 2px */
  /* Reduce the gap between the tabs */
  -moz-margin-start: -0.8px;  /* was -1px */
}
```
@Lootyhoof did I understand how this half-transparent border works properly? it's been a while since I looked at this.
It's also possible we have influenced some of our other themes with this change in border rounding if they use similar hacks; probably worth to check.
