### ISSUE TITLE
Improve AppMenu's visual speed?

### ISSUE THREAD

**Issue by Self-Referential-Drama** [MoonchildProductions/Pale-Moon#20]
Unsure if you would like this improvement as it modifies the layout. (Barely, but still.)

Currently both on Linux and Windows, the AppMenu is visually slow for many users, because of the CSS for appmenuSecondaryPane. (The difference is mainly visable on Windows.)

Currently the CSS used is box-shadow, -moz-border-colors should be used instead of the slower box-shadow CSS.

Current CSS:
```
/* browser/themes/windows/browser.css */
#appmenuSecondaryPane {
 background-color: #f1f5fb;
 box-shadow: 1px 0 2px rgb(204,214,234) inset;
 padding-bottom: 2px;
 font-family: "Segoe UI Semibold", "Segoe UI", sans-serif;
}
```

CSS with changes applied:
```
/* browser/themes/windows/browser.css */
#appmenuSecondaryPane {
  border-left: 5px solid !important;
  -moz-border-left-colors: #CCD9EA #D9E3F0 #E8EEF7 #EDF2F9 #F0F4FA !important;
}
```

A simple UserStyle can achieve the change:
https://userstyles.org/styles/110186/pale-moon-appmenu-experiment

So it is up to you if you want to integrate this change, if you do I will open a pull request for it, if you do not want to, it can stay as a UserStyle.

**Comment by wolfbeast** [comment]
I tinkered with it a little since I didn't like the effect (mainly because it makes it darker and thicker (5px vs a 1+2px shadow))

An improvement would be using the following instead which seems to make it IMO better than the original (a little sharper):
```css
#appmenuSecondaryPane {
 background-color: #f1f5fb;
 border-left: 3px solid;
 -moz-border-left-colors: #CCD9EA #E8EEF7 #F0F4FA;
 padding-bottom: 2px;
 font-family: "Segoe UI Semibold", "Segoe UI", sans-serif;
}
```

See what you think of it - I haven't had time to test this in different windows themes/color schemes so if it pans out there, feel free to make a pull request.
